### ISSUE TITLE
not compatible with Salt Cloud Linode provider

### ISSUE THREAD

**Issue by blbradley** [saltstack-formulas/hostsfile-formula#22]
Salt Cloud's Linode provider has strict rules on the label used for a VM's name:

```
[WARNING ] A Linode label may only contain ASCII letters or numbers, dashes, and underscores, must begin and end with letters or numbers, and be at least three characters in length.
```

Because dots are not allowed, a full domain name cannot be set as the minion ID. This is incompatible with the requirement of matching the minion ID to the FQDN.

I'll attempt to add an option to improve this.

**Comment by johnkeates** [comment]
Does Linode allow dots?

**Comment by blbradley** [comment]
No. I'm not sure if the restriction is due to the Salt Cloud implementation or the Linode API.
