### ISSUE TITLE
Typo in state

### ISSUE THREAD

**Issue by ricariel** [saltstack-formulas/hostsfile-formula#39]
```diff
$ diff --git a/hostsfile/hostname.sls b/hostsfile/hostname.sls
index 60a6671..d137124 100644
--- a/hostsfile/hostname.sls
+++ b/hostsfile/hostname.sls
@@ -33,7 +33,7 @@ hostsfile-etc-sysconfig-network:
     - backup: false
 {% endif %}
     - onchanges_in:
-      - cmd: set-fqdn
+      - cmd: hostsfile-set-fqdn
 
 hostsfile-{{ fqdn }}-hosts-entry:
   host.present:
```

**Comment by myii** [comment]
Thanks for the report, @ricariel.

This was introduced in #36, which then had the state ID adjusted in #37.  @noelmcloughlin, would you like to resolve this either way?

In fact, there's even a comment about it from @aboe76 [here](https://github.com/saltstack-formulas/hostsfile-formula/pull/36/files#r702463791).

**Comment by noelmcloughlin** [comment]
Thanks @ricariel @myii  PR raised https://github.com/saltstack-formulas/hostsfile-formula/issues/39
