### ISSUE TITLE
Unused line of code, remove or update readme

### ISSUE THREAD

**Issue by samos123** [saltstack-formulas/hostsfile-formula#7]
The following line seems no longer being used?

`{%- set if = grains['maintain_hostsfile_interface'] %}`

If it's still in use we should update readme, if it's not in use anymore maybe we can remove it. also setting a variable name to be if is really confusing as if can also be an if statement.

Link to code:
https://github.com/saltstack-formulas/hostsfile-formula/blob/master/hostsfile/init.sls#L15

**Comment by aboe76** [comment]
@samos123 can this issue be closed? because of merge #8
